### ISSUE TITLE
How to respond to "Call for Makers"?

### ISSUE THREAD

**Issue by KatieK2** [cascadiajs/2014.cascadiajs.com#162]
Hi! The link in "Go to the Call for Makers new issue" in the CFM readme doesn't work. Am I just supposed to use the CfM label for a new issue?

**Comment by hackygolucky** [comment]
Oh no! It's just supposed to take you to a new issue in the
2014.cascadiajs.com repo and we'd tag it with the CfM label.

Is it just a broken link? It worked for me.

**Comment by KatieK2** [comment]
Right, the link fails for me: https://github.com/cascadiajs/2014.cascadiajs.com/call-for-makers/issues/new gives a 404 error.

**Comment by hackygolucky** [comment]
Fixed! Changed the link because I derpily set it to the directory which you can't create new issues from. For the most part. I think only admins have the ability to apply the Call for Makers label. Oh permissions...
