### ISSUE TITLE
"Webji II: The WebSocketing" by Randall A. Gordon

### ISSUE THREAD

**Issue by randallagordon** [cascadiajs/2014.cascadiajs.com#173]
# "Webji II: The WebSocketing"

Randall A. Gordon
[randall@randallagordon.com](mailto:randall@randallagordon.com)

Many moons ago, when the Palm Pre came out, I made a silly little demo that used the Pre's accelerometer to control a virtual ouija board which I called [Webji](http://webji.mndktchn.com/).

![image](https://cloud.githubusercontent.com/assets/635388/3449845/896799a8-016d-11e4-9582-c6854db7e77e.png)

Which was fun. But, I've always wanted to make a physical version of the board which is controlled by **MAGIC!** Which is to say, via a magnet being moved around by stepper motors underneath a CNC milled version of the ouija board.

It seems to me like CascadiaJS is the _perfect_ reason to convert the server over to Node.js and call on some of my best friends—WebSockets and `node-serialport`—to make a JavaScript-powered talking board a reality!

The software is already ready to go...part of it is just in Ruby at the moment! I'll get that aspect taken care of pronto. Just need to buy some motors, rescue a nice, strong magnet from an old hard drive and start milling parts to take care of the hardware end of things.

**Comment by hackygolucky** [comment]
@randallagordon GO GO GO! 

When you're ready for reimbursement, just email the receipts(can be photos if need be) and the email address we can refund you via PayPal to info@cascadiajs.com

We're going to have an email list for Makers that will probably have an email or two go out regarding logistics of setup and what we can do to help make this process better for you. Thanks!!!
