### ISSUE TITLE
Provide option to NOT print handles/names on hoodies

### ISSUE THREAD

**Issue by KatieK2** [cascadiajs/2014.cascadiajs.com#186]
Some people love having their handles/names on their hoodies. Some people hate it. For cascadiajs.next, please allow an option for attendees to have a generic hoodie without any name/handle information on it.

Thanks!

**Comment by kenperkins** [comment]
+1

**Comment by hackygolucky** [comment]
LOL if I didn't see this coming :)

**Comment by jonmadison** [comment]
+1

**Comment by KatieK2** [comment]
If there was a CJS 2015, I'd have filed the issue there.  :) Thanks for listening!

**Comment by junosuarez** [comment]
Do we have any blank hoodies left over, @hackygolucky?

**Comment by hackygolucky** [comment]
@jden Nope! Those suckers were pricey. We had about 30 blanks and they went
fast.

**Comment by KatieK2** [comment]
Can you provide technical specs on what was used for printing? Perhaps with a carefully selected solvent...

**Comment by hackygolucky** [comment]
The name on the sleeve is not screenprinted, it is heat transferred. That's
all that I'm aware of.

**Comment by junosuarez** [comment]
A quick search for "remove heat transfer" seems promising! Please post here if you find something that works.

**Comment by KatieK2** [comment]
Cross-posted to CJS 2015, so closing this issue.
